### ISSUE TITLE
Increasing Java Heap Space

### ISSUE THREAD

**Issue by RossWickham** [mkoohafkan/dssrip2#4]
May want to suggest users increase Java heap space options prior to initializing dssrip2, or do this as a default behavior. I have received the following error running dss_catalog function:

java.lang.OutOfMemoryError: GC overhead limit exceeded

Setting option to increase JVM heap space resolved issue:

options(java.parameters = "-Xmx8000m")

**Comment by mkoohafkan** [comment]
`java.parameters` is evaluated exactly once per R session when the JVM is initialized, i.e., usually when the first package that uses Java is loaded. Therefore I don't think it's safe to have `dssrip2` set the options on load, just in case the user loaded `rJava` (or another `rJava`-dependent package) first.

I think adding some info on Java parameters to the `dss_connect()` documentation, and perhaps a vignette listing recommended options for `dssrip2` and likely causes of common Java errors, would be a good idea and provide sufficient direction to users.

**Comment by mkoohafkan** [comment]
Closed via 5ea5942489a407a7e52e488ce6def80e3a8fc46b, c7700995829e5930e0f591d0bb3137aa65779af9

**Comment by eheisman** [comment]
Meant to get add this yesterday but network issues were preventing me from getting in:

If you use the `.jpackage()` call to initialize the JVM in the package `.onLoad` function, it will avoid resetting the parameters for an existing JVM.  You should still be able to warn the user that parameters will not be used if the JVM is already initialized.
